apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: incident-log-gitops-repo
  namespace: incident-log
spec:
  interval: 1m0s
  ref:
    branch: main
  timeout: 1m0s
  url: https://github.com/acidnyi/incident-gitops