apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

labels:
  - pairs:
      app.kubernetes.io/part-of: incident-log
      app.kubernetes.io/name: incident-log

namespace: incident-log

resources:
  - cd.kustomization.yaml
  - install.kustomization.yaml
  - git-repository.yaml