apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: wac-hospital

labels:
  - pairs:
      app.kubernetes.io/part-of: incident-log
      app.kubernetes.io/name: incident-log
    includeSelectors: true
    includeTemplates: true

resources:
  - ../../../apps/incident-log

components:
  - ../../../components/version-release