apiVersion: polyfea.github.io/v1alpha1
kind: WebComponent
metadata:
  name: incident-log-content
spec:
  microFrontend: incident-log
  element: incident-app
  attributes:
    - name: base-path
      value: /incident-log
    - name: api-base
      value: /incident-log-api
    - name: entryId
      value: INC-001
  displayRules:
    - allOf:
        - context-name: main-content
        - path: "^(\\.?/)?incident-log(/.*)?$"