apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: incident-log 

labels:
- pairs:
    app.kubernetes.io/part-of: incident-log

resources:
- ../../../apps/incident-log

components:
- ../../../components/version-developers